### ISSUE TITLE
Non-Active Window - Color Changes on Browser Tabs

### ISSUE THREAD

**Issue by swolfe2** [drunkzurg/ColorfulChromium#1]
Great job on these themes!

I am really liking the Gruvbox one. However, I've noticed that whenever I click from one Edge window to another, the tab colors will switch to this red color when not in vertical tabs. Is there a configuration to make them keep their same previous colors when it is not the active window?

When in active window:
![image](https://github.com/drunkzurg/OpenColors/assets/36700028/97f48837-feb7-4c78-9e66-d46dbe377410)

When not in active window:
![image](https://github.com/drunkzurg/OpenColors/assets/36700028/6bfe4a59-1029-4b93-bd9c-29ed577cc25f)

I believe it may be this section:
![image](https://github.com/drunkzurg/OpenColors/assets/36700028/b9b647bd-a1db-437b-a9cb-d094c9566fb3)

Thanks!

**Comment by drunkzurg** [comment]
Thank you! You're right, those are the required RRG color codes. You can change it to [30, 32, 33] to blend with the background. If you are using the non-vertical tab configuration, you can also change the color of window control buttons to flush them with the browser;
**"button_background": [40, 40, 40],** to **"button_background": [30, 32, 33],**

The forward and backward buttons are almost invisible too which might cause some people accessibility issues. You can change their color in the <strong>"toolbar_button_icon"</strong> attribute.
If you dont see any change when rewriting the color codes, you might have to delete the "CachedTheme.pak" file and reload the extension.

Here's a folder with those your required change applied, let me know if there's any problem. 
[gruvbox.zip](https://github.com/drunkzurg/OpenColors/files/11498964/gruvbox.zip)

**Comment by swolfe2** [comment]
Ok, great! Thanks for the awesome answer and the file. Also, thanks for the information about the button background. Really great work with this, I appreciate it.
